## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

###################################
## Must disable USE_CUDNN and ENABLE_INQ
#ENABLE_PRINT_MIN_MAX := 1 
#USE_CUDNN := 1
#ENABLE_INQ := 1


# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda-8.0

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_50,code=compute_50

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := mkl
BLAS_INCLUDE := $(HOME)/sandbox/3rdparty/include
BLAS_LIB := $(HOME)/sandbox/3rdparty/lib/

# Anaconda Python distribution is quite popular. Include path:                                                                    
# Verify anaconda location, sometimes it's in root.                                                                               
ANACONDA_HOME := $(HOME)/sandbox/3rdparty/anaconda
PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
               $(ANACONDA_HOME)/include/python2.7 \
               $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include \

PYTHON_LIB := $(ANACONDA_HOME)/lib

# Whatever else you find you need goes here.                                                                                      
INCLUDE_DIRS := $(HOME)/sandbox/3rdparty/include $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(HOME)/sandbox/3rdparty/lib $(PYTHON_LIB) /usr/local/lib /usr/lib

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171                                   
# DEBUG := 1                                                                                                                      

# The ID of the GPU that 'make runtest' will use to run unit tests.                                                               
TEST_GPUID := 0

#CXXFLAGS += ENABLE_LOG_IN_FORWARD                                                                                                
# enable pretty build (comment to see full commands)                                                                              
Q ?= @


